ip: "127.0.0.1:4567"
autoMigrate: true
dsn: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
schemaName: "my_little_ps"
prefork: false
idleTimeoutSec: 60
readTimeoutSec: 60
writeTimeoutSec: 60
shutdownTimeoutSec: 90
